{% set name = "swiftbat" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/swiftbat-{{ version }}.tar.gz
  sha256: 718fa96638f0de4389a971ea26d4c8c35dddeb1c33562f3486c13d4aa4666a26

build:
  entry_points:
    - swinfo=swiftbat.swinfo:swinfo_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - astropy-base >=5
    - astroquery
    - numpy
    - python-dateutil
    - skyfield >=1.4
    - swifttools

test:
  imports:
    - swiftbat
  commands:
    - pip check
    - swinfo --help
  requires:
    - pip

about:
  home: https://github.com/lanl/swiftbat_python/
  summary: Routines for dealing with data from BAT on the Neil Gehrels Swift Observatory
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaeakle
